stages:
    - build
    - test

build:
    stage: build
    image: node
    script:
        - echo "Start building App"
        - npm install
        - npm run build
        - echo "Build successfully!"
    artifacts:
        expire_in: 1 hour
        paths:
            - build
            - node_modules/

test:
    stage: test
    image: node
    script:
        - echo "Testing App"
        - npm install
        - CI=true npm test
        - echo "Test successfully!"

docker-build:
    stage: docker-build
    image: docker:latest
    services:
        - name: docker:19.03.8-dind
    script:
        - docker build -t loft-traveler .
